# This workflow will do a clean install of .net dependencies, build the source code and run tests across different versions of .net
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-net-with-github-actions

name: .NET CI

on:
  push:
    branches: [ main, 1.x ]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use .NET "6.0.x"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    # MISSING LINT

  unit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use .NET "6.0.x"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test Unit
      run: dotnet test --no-build --verbosity normal --filter "TestU"

  integration:
    runs-on: ubuntu-latest

    services:
      rippled:
        image: natenichols/rippled-standalone:latest
        ports:
        - 6006:6006
        options:
          --health-cmd="wget localhost:6006 || exit 1" --health-interval=5s --health-retries=10 --health-timeout=2s

    steps:
    - uses: actions/checkout@v3
    - name: Use .NET "6.0.x"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test Unit
      run: dotnet test --no-build --verbosity normal --filter "TestI"
      env:
        HOST: localhost
        PORT: ${{ job.services.rippled.ports['6006'] }}